### ISSUE TITLE
Can't find transaction

### ISSUE THREAD

**Issue by purpurato** [btcontract/wallet#110]
I just installed the testnet wallet and sent some tBTC there but I just can't see them on the wallet, the transaction has already 6+ blocks confirmed, this is the txid
cec1da1d6d18f8eef3d7a5793ae7039bdc5720e79d32d70617a77be34903b941
but still don't see it there. I double checked the address and confirmations. Is there a sync problem maybe?

**Comment by btcontract** [comment]
This is likely either a connectivity issue (no Electrum node is connected) or wallet still synchronizing, it can take a few minutes on testnet.

Unfortunately current testnet version is old and shows no connectivity or sync details, I'll update it this week so you'll be able to see what exactly is going on.

**Comment by purpurato** [comment]
Yes, I believe there was a sync issue so I changed the Electrum node and now the transaction is there. Thanks for your answer and looking forward to an updated version. 
Cheers

**Comment by purpurato** [comment]
I would like to create channels and send payments to/from the wallet but something is not active on the testnet version. Would be nice to update testnet version. 
Thanks

**Comment by btcontract** [comment]
Testnet version `2.4.19` has been uploaded to Play store, should be available shortly.

**Comment by purpurato** [comment]
Thanks for the update. This is what I got when opening after new version installed. 


android.database.sqlite.SQLiteException: no such table: cwallet (code 1 SQLITE_ERROR[1]): , while compiling: SELECT * FROM cwallet ORDER BY _id ASC
 at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
 at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1463)
 at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:901)
 at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
 at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:62)
 at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
 at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
 at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:2063)
 at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:2002)
 at com.btcontract.wallettest.sqlite.DBInterfaceSQLiteAndroid$class.select(DBInterfaceSQLiteAndroid.scala:15)
 at com.btcontract.wallettest.sqlite.DBInterfaceSQLiteAndroidMisc.select(DBInterfaceSQLiteAndroidMisc.scala:8)
 at immortan.sqlite.SQLiteChainWallet.listWallets(SQLiteChainWallet.scala:27)
 at com.btcontract.wallettest.WalletApp$.makeOperational(WalletApp.scala:201)
 at com.btcontract.wallettest.MainActivity$EnsureSeed.makeAttempt(MainActivity.scala:109)
 at com.btcontract.wallettest.MainActivity$EnsureAuth$$anon$1.onAuthSucceeded(MainActivity.scala:158)
 at com.btcontract.wallettest.utils.BiometricAuth$$anon$1.onAuthenticationSucceeded(BiometricAuth.scala:38)
 at androidx.biometric.BiometricFragment$9.run(BiometricFragment.java:907)
 at android.os.Handler.handleCallback(Handler.java:938)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:246)
 at android.app.ActivityThread.main(ActivityThread.java:8528)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by btcontract** [comment]
It's probably not backwards compatible, I care about this stuff in mainnet version, but not in testnet. Just reinstall an app from scratch and it will work.

**Comment by purpurato** [comment]
I did something pretty stupid :( 
I have both testnet and mainnet wallets installed on my phone and accidentally deleted the mainnet app. Can you please give me a hint as where to find the wallet data and if it's possible to restore that file? I am looking for info recovering deleted apps, but I am not even sure which file to look for. I didn't really deleted the whole app, but I went to the settings menu and deleted data there. 
Thanks for your help, sorry to bother you with this unrelated issue.

**Comment by btcontract** [comment]
The important thing here is to have a recovery phrase, have you got it? If yes then just reinstall from scratch and restore using backup file in Download folder: https://sbw.app/posts/manual/#wallet-restoring

But wallet backup alone won't help since it only stores channel data (if there are any channels) and is itself encrypted with recovery phrase.

As to app un-deletion, can't say anything definite here.
