### ISSUE TITLE
Error when trying to create incoming channel from c-lightning node

### ISSUE THREAD

**Issue by raphjaph** [btcontract/wallet#136]
I tried opening a private channel from a c-lightning node to SBW but SBW then gives me the following error:

![IMAGE 2021-12-30 19:23:29](https://user-images.githubusercontent.com/25913312/147778424-3034fb1c-09c0-4135-ba17-c04dc4ab9b3f.jpg)

``` 
java.lang.IllegalStateException: You must either set a text or a view
	at com.android.internal.util.Preconditions.checkState(Preconditions.java:173)
	at android.widget.Toast.show(Toast.java:188)
	at com.btcontract.wallet.WalletApp.quickToast(WalletApp.scala:425)
	at com.btcontract.wallet.RemotePeerActivity$$anonfun$revertAndInform$1.apply$mcV$sp(RemotePeerActivity.scala:304)
	at com.btcontract.wallet.RemotePeerActivity$$anonfun$revertAndInform$1.apply(RemotePeerActivity.scala:300)
	at com.btcontract.wallet.RemotePeerActivity$$anonfun$revertAndInform$1.apply(RemotePeerActivity.scala:300)
	at com.btcontract.wallet.BaseActivity$$anon$8.run(BaseActivity.scala:242)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```

These are the c-lightning debug logs:
```
"type": "INFO",
         "time": "67678.359092609",
         "source": "lightningd",
         "log": "Will open private channel with node *********8160"
      },
      {
         "type": "SKIPPED",
--
      {
         "type": "DEBUG",
         "time": "67678.469310108",
         "node_id": "*******8160",
         "source": "openingd-chan#199",
         "log": "billboard: Funding channel start: awaiting funding_txid with output to 0020f451d057474924a5e2ef7b4dc2e7fd413c69e3904783a95e08d2154fdd6abdf8"
      },
--
         "type": "DEBUG",
         "time": "67678.469805007",
         "source": "plugin-spenderp",
         "log": "mfc 80810, dest 0: fundchannel_start ********8160 done."
      },
      {
         "type": "SKIPPED",
--
         "type": "DEBUG",
         "time": "67678.469860987",
         "source": "plugin-spenderp",
         "log": "mfc 80810: funding tx cbd5bf744a9caacb661d6240584e1a949eaf34fa25af8c61d91997852e2af125: ********8160: 20000sat, change: 351683sat"
      },
      {
         "type": "DEBUG",
--
         "type": "DEBUG",
         "time": "67678.469874120",
         "source": "plugin-spenderp",
         "log": "mfc 80810, dest 0: fundchannel_complete *******8160."
      },
      {
         "type": "SKIPPED",
--
      {
         "type": "DEBUG",
         "time": "67678.471527152",
         "node_id": "********8160",
         "source": "openingd-chan#199",
         "log": "billboard: Funding channel con't: continuing with funding_txid cbd5bf744a9caacb661d6240584e1a949eaf34fa25af8c61d91997852e2af125"
      },
--
      {
         "type": "DEBUG",
         "time": "67678.473462006",
         "node_id": "******8160",
         "source": "openingd-chan#199",
         "log": "peer_out WIRE_FUNDING_CREATED"
      },
      {
         "type": "DEBUG",
         "time": "67678.473623351",
         "node_id": "*******8160",
         "source": "openingd-chan#199",
         "log": "billboard: Funding channel: create first tx, now waiting for their signature"
      },
--
      {
         "type": "DEBUG",
         "time": "67678.633633843",
         "node_id": "******8160",
         "source": "openingd-chan#199",
         "log": "Status closed, but not exited. Killing"
      },
      {
         "type": "INFO",
         "time": "67678.636395980",
         "node_id": "******8160",
         "source": "chan#199",
         "log": "Owning subdaemon openingd died (62208)"
      },
--
      {
         "type": "DEBUG",
         "time": "67678.637374521",
         "node_id": "*****8160",
         "source": "connectd",
         "log": "disconnect"
      },

```

It looks like SBW cancels the channel opening, but I'm not sure if I read this correctly. Is there somewhere on my phone where I can look at the full SBW logs?

**Comment by btcontract** [comment]
What's your app version (can be seen on settings page)? There used to be a bug which behaved like this and it's fixed in last version.

**Comment by raphjaph** [comment]
v2.4.23-91

**Comment by btcontract** [comment]
The latest one is `2.4.24-92`, can you please check if issue persists with it?

**Comment by raphjaph** [comment]
Ah ok, yes works now
