### ISSUE TITLE
App just closes and needs to be reinstalled and synced every time 

### ISSUE THREAD

**Issue by nouser55** [btcontract/wallet#45]
time: 1571517213540
msg: org.bitcoinj.wallet.UnreadableWalletException: Transaction did not deserialize completely: 45c3ea4275c3846f9be592ae5aa8a534d63482bcfa00dee5039dd84247f141f4 vs 1bef12cba300faafb36b8b529dfe284dc1328a719cdf51b2a23ce33cee8a8b7d
stacktrace: java.lang.RuntimeException: org.bitcoinj.wallet.UnreadableWalletException: Transaction did not deserialize completely: 45c3ea4275c3846f9be592ae5aa8a534d63482bcfa00dee5039dd84247f141f4 vs 1bef12cba300faafb36b8b529dfe284dc1328a719cdf51b2a23ce33cee8a8b7d
	at com.google.common.base.Throwables.propagate(Throwables.java:160)
	at com.google.common.util.concurrent.AbstractIdleService$2$1.run(AbstractIdleService.java:58)
	at com.google.common.util.concurrent.Callables$3.run(Callables.java:95)
	at java.lang.Thread.run(Thread.java:764)
Caused by: org.bitcoinj.wallet.UnreadableWalletException: Transaction did not deserialize completely: 45c3ea4275c3846f9be592ae5aa8a534d63482bcfa00dee5039dd84247f141f4 vs 1bef12cba300faafb36b8b529dfe284dc1328a719cdf51b2a23ce33cee8a8b7d
	at org.bitcoinj.wallet.WalletProtobufSerializer.readTransaction(WalletProtobufSerializer.java:667)
	at org.bitcoinj.wallet.WalletProtobufSerializer.readWallet(WalletProtobufSerializer.java:503)
	at org.bitcoinj.wallet.WalletProtobufSerializer.readWallet(WalletProtobufSerializer.java:440)
	at com.btcontract.wallet.MainActivity$$anon$1.startUp(MainActivity.scala:66)
	at com.google.common.util.concurrent.AbstractIdleService$2$1.run(AbstractIdleService.java:54)
	... 2 more

**Comment by btcontract** [comment]
Do you have a mnemonic code? Simple Bitcoin Wallet is no longer maintained, it's advised to restore balance in a another wallet and move on with that one. Derivation path for mnemonic is `m/0'`, compatible wallets can be found here: https://walletsrecovery.org/
