### ISSUE TITLE
The app is extremely slow

### ISSUE THREAD

**Issue by rkfg** [btcontract/wallet#50]
Sent a report about ANR. The app is so slow it takes a minute to switch between activities (it shows a black screen but then the expected window appears). It's still opening a channel (only 1 conf) and just by tapping some items on the screen (on-chain wallet, settings, usage stats) it slows down to a crawl, eventually showing "Something went wrong" and the report says:
```
java.util.concurrent.TimeoutException: com.android.internal.os.BinderInternal$GcWatcher.finalize() timed out after 10 seconds
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:442)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:190)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:211)
	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:271)
	at java.lang.Daemons$Daemon.run(Daemons.java:137)
	at java.lang.Thread.run(Thread.java:919)
```

**Comment by btcontract** [comment]
Can you plase share your Android version and phone model?

**Comment by rkfg** [comment]
Moto G7 Power, Android 10. I made a video that shows that the app is almost unresponsive while the rest of the system works fine: https://www.youtube.com/watch?v=3CRER08OoNU

**Comment by btcontract** [comment]
Will try to reproduce this on identical phone model, will have that model closer to the end of next week.

**Comment by btcontract** [comment]
So far was not able to reproduce this on an identical phone model. 

Can you check if these issues persist with latest update? Latest update version is v2.0.5-65, can be seen in app settings.

**Comment by rkfg** [comment]
Worked fine for a short while, then crashed with this stack trace:
```
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw an exception; no stack trace available
```
Then after restarting the app it behaved like before, fast at first then rapidly slowing down and crashing. The latest crash message says:
```
java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 16 free bytes and 16B until OOM, target footprint 100663296, growth limit 100663296
	at scodec.bits.ByteVector$.view(ByteVector.scala:1501)
	at immortan.sqlite.RichCursor$class.byteVec(RichCursor.scala:10)
	at com.btcontract.wallet.sqlite.RichCursorSQLiteAndroid.byteVec(RichCursorSQLiteAndroid.scala:9)
	at immortan.sqlite.SQLiteNetwork$$anonfun$listChannelAnnouncements$1.apply(SQLiteNetwork.scala:64)
	at immortan.sqlite.SQLiteNetwork$$anonfun$listChannelAnnouncements$1.apply(SQLiteNetwork.scala:61)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at com.btcontract.wallet.sqlite.RichCursorSQLiteAndroid$$anon$1.foreach(RichCursorSQLiteAndroid.scala:29)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at com.btcontract.wallet.sqlite.RichCursorSQLiteAndroid.foreach(RichCursorSQLiteAndroid.scala:9)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at com.btcontract.wallet.sqlite.RichCursorSQLiteAndroid.map(RichCursorSQLiteAndroid.scala:9)
	at com.btcontract.wallet.sqlite.RichCursorSQLiteAndroid.iterable(RichCursorSQLiteAndroid.scala:10)
	at immortan.sqlite.SQLiteNetwork.listChannelAnnouncements(SQLiteNetwork.scala:61)
	at immortan.sqlite.SQLiteNetwork.getRoutingData(SQLiteNetwork.scala:88)
	at immortan.PathFinder.doProcess(PathFinder.scala:138)
	at immortan.PathFinder$$anonfun$process$1.apply$mcV$sp(PathFinder.scala:49)
	at immortan.PathFinder$$anonfun$process$1.apply(PathFinder.scala:49)
	at immortan.PathFinder$$anonfun$process$1.apply(PathFinder.scala:49)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
```
I have many apps installed and sure some of them leave their services running in the background. But I've never seen Android apps OOMing like that and slowdowns sure look like a case of extreme thrashing (like on desktop Linux).

**Comment by btcontract** [comment]
Well at least this is a progress: an error message has changed and apparently it's something about graph data taking up too much memory, which is more understandable than previous error messages.

So the task seems to be reducing app memory footprint and react appropriately when out-of-memory is looming. I'll keep investigating how to achieve both of these in subsequent updates and we can keep trying if that works if you don't mind?

**Comment by rkfg** [comment]
Sure, no problem. The messages are indeed different, looks like it doesn't always produce a full stack trace depending on how _hard_ it runs out of memory. Thing is, I wasn't doing anything heavy (no transactions or such) before I got this, just opened settings and LN/On-chain properties, scrolled back and forth and so on. Basically the same I did in the video above, it took a little longer for the app to start freezing and crashing.

I expect Android to terminate services and kill other apps if it's low on memory, I wonder why it doesn't happen here. Or does SBW run out of its own heap memory? In that case can it be increased in the manifest or such? I only developed for Android briefly and I don't know if such low level stuff is possible there.

**Comment by btcontract** [comment]
I have no idea yet as this is the first time I encounter something like this, will look into all possible options. 

Maybe there's a memory leak of some kind, for example a wallet with a fully loaded graph constantly takes about 137mb of RAM on my phone which is sizeable but not catastrophically large.

I guess the first thing to do is set up a "too much memory is taken" listener and provide a detailed report which for example you can post here, that will be done in next update.

**Comment by rkfg** [comment]
I installed the .apk from the Releases tab and so far it seems to work fine. I'll use the app more and if there are no issues will close this issue in a few days. Thanks!
