### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by rkfg** [btcontract/wallet#67]
Got a crash with the following traceback straight after launching the app:
```
java.lang.RuntimeException: Unable to destroy activity {com.btcontract.wallet/com.btcontract.wallet.HubActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'akka.actor.ActorRef immortan.LNParams$WalletExt.catcher()' on a null object reference
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5176)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5205)
	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2183)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:241)
	at android.app.ActivityThread.main(ActivityThread.java:7604)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'akka.actor.ActorRef immortan.LNParams$WalletExt.catcher()' on a null object reference
	at com.btcontract.wallet.HubActivity.onDestroy(HubActivity.scala:733)
	at android.app.Activity.performDestroy(Activity.java:8068)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1363)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5161)
	... 11 more
```

I remember swiping it off of the recent app list hours ago so that's probably related.

**Comment by btcontract** [comment]
Most likely fixed in https://github.com/btcontract/wallet/commit/7ad94c13dd6f45077edf1c8c9a2a7515afe260e9.

Due to Android specifics an app may become half-destroyed so to say: some objects may be nullified while others remain in place. 

So when launched an app may find itself in such a state, in which case it destroys itself completely and restarts. The issue most likely is that app was trying to access already nullified object properties in `onDestroy` method, which resulted in exception.

Now those parts are surrounded by `try` blocks which swallow exceptions allowing an app to restart cleanly.

**Comment by btcontract** [comment]
Let's see if this happens again within some time after next update, if not then I'll close an issue.

**Comment by btcontract** [comment]
Closing this for now, feel free to reopen if this happens again.
